#!/usr/bin/env node
// Compare the live prod schema (via Supabase Management API) against the
// committed baseline supabase/migrations/20260101000000_remote_schema.sql.
//
// Exit 0 -> identical. Exit 1 -> drift detected; a unified diff is printed
// to stdout. The header line "Generated by scripts/export-schema.mjs on
// <ISO>" is stripped from both sides before diffing so the timestamp does
// not produce false positives.
//
// Usage:
//   $env:SUPABASE_ACCESS_TOKEN = "sbp_..."
//   pnpm db:check-drift
//
// This is the safety net for the Sprint Refactor R0 post-mortem (see
// docs/audit/POST-MORTEM-C3-DRIFT.md). It catches the case where prod and
// the committed baseline have silently diverged — exactly what happened
// when the C3 RPC migration was marked applied without its SQL ever
// executing.

import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { dirname } from 'node:path'

import { buildBaseline } from './export-schema.mjs'

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const BASELINE_PATH = resolve(
  REPO_ROOT,
  'supabase/migrations/20260101000000_remote_schema.sql'
)

const TIMESTAMP_LINE = /^-- Generated by scripts\/export-schema\.mjs on .+$/

function stripTimestamp(sql) {
  return sql
    .split('\n')
    .filter((line) => !TIMESTAMP_LINE.test(line))
    .join('\n')
}

// Tiny line-level unified diff. Adequate for a human-readable signal — we do
// not need full Myers diff resolution because the export is deterministic
// (every query in scripts/export-schema.mjs orders by stable keys).
function unifiedDiff(expected, actual) {
  const expectedLines = expected.split('\n')
  const actualLines = actual.split('\n')
  const out = []
  out.push('--- supabase/migrations/20260101000000_remote_schema.sql (committed)')
  out.push('+++ live prod schema (via Management API)')

  const max = Math.max(expectedLines.length, actualLines.length)
  let removed = 0
  let added = 0
  for (let i = 0; i < max; i++) {
    const e = expectedLines[i]
    const a = actualLines[i]
    if (e === a) continue
    if (e !== undefined) {
      out.push(`-${i + 1}: ${e}`)
      removed++
    }
    if (a !== undefined) {
      out.push(`+${i + 1}: ${a}`)
      added++
    }
  }
  out.push(`\nSummary: ${removed} line(s) only in committed baseline, ${added} line(s) only in live prod.`)
  return out.join('\n')
}

async function main() {
  const liveRaw = await buildBaseline()
  let committedRaw
  try {
    committedRaw = readFileSync(BASELINE_PATH, 'utf8')
  } catch (err) {
    console.error(`ERROR: cannot read committed baseline at ${BASELINE_PATH}: ${err.message}`)
    process.exitCode = 2
    return
  }

  // Normalize CRLF → LF BEFORE stripTimestamp. buildBaseline() emits LF
  // (parts.join('\n')); the on-disk baseline can be CRLF on Windows working
  // copies after `git checkout` if core.autocrlf=true. CRLF also breaks
  // the TIMESTAMP_LINE regex (`.+$` does not consume `\r` in JS), so without
  // normalizing first the timestamp line is NOT stripped from the committed
  // file, producing a one-line shift and a fully-spurious diff.
  const normalize = (s) => stripTimestamp(s.replace(/\r\n/g, '\n')).trimEnd()
  const live = normalize(liveRaw)
  const committed = normalize(committedRaw)

  if (live === committed) {
    console.error('OK: prod schema matches committed baseline.')
    process.exitCode = 0
    return
  }

  console.error('DRIFT DETECTED: prod schema differs from committed baseline.')
  console.error('To resolve: run `node scripts/export-schema.mjs supabase/migrations/20260101000000_remote_schema.sql`,')
  console.error('inspect the diff, and either commit the new baseline (if prod is the source of truth)')
  console.error('or push the missing migrations (if the repo is the source of truth).')
  console.error('')
  process.stdout.write(unifiedDiff(committed, live) + '\n')
  process.exitCode = 1
}

// Use process.exitCode (not process.exit) so Node drains the undici keep-alive
// sockets cleanly. process.exit() while sockets are closing triggers a libuv
// assertion on Windows (`!(handle->flags & UV_HANDLE_CLOSING)`).
main().catch((err) => {
  console.error('FATAL:', err.message)
  process.exitCode = 2
})
