#!/usr/bin/env node
// Compose a baseline `supabase/migrations/<ts>_remote_schema.sql` against
// the Popoth prod project via the Supabase Management API. Docker-less.
//
// Usage (PowerShell — pass output path; the script writes UTF-8 directly so
// PowerShell's `>` UTF-16 default does not mangle the file):
//   $env:SUPABASE_ACCESS_TOKEN = "sbp_..."
//   node scripts/export-schema.mjs supabase/migrations/20260101000000_remote_schema.sql
//
// Without an output path argument the script prints to stdout (UTF-8). On
// PowerShell, prefer the path form to avoid encoding issues.
//
// What it captures:
//   extensions, tables (columns + defaults + nullability), PK / UNIQUE,
//   foreign keys, CHECK constraints, non-implicit indexes, RLS-enable
//   statements, policies, triggers, sequences owned by columns.
//
// What it does NOT capture:
//   functions / RPCs (those live in supabase/migrations/*_create_finance_rpcs.sql
//   and any future RPC migrations), grants/revokes outside RLS, custom
//   types beyond enums, materialized views.

import { writeFileSync } from 'node:fs'

const PROJECT_REF = process.env.SUPABASE_PROJECT_REF ?? 'jzmppreybwabaeycvasz'
const TOKEN = process.env.SUPABASE_ACCESS_TOKEN
const OUT_PATH = process.argv[2] // optional: write to file instead of stdout

if (!TOKEN) {
  console.error('ERROR: set $env:SUPABASE_ACCESS_TOKEN before running.')
  process.exit(1)
}

const URL = `https://api.supabase.com/v1/projects/${PROJECT_REF}/database/query`

const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

async function query(sql, attempt = 0) {
  let res
  try {
    res = await fetch(URL, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${TOKEN}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ query: sql }),
    })
  } catch (err) {
    if (attempt < 3) {
      const wait = 500 * Math.pow(3, attempt)
      console.error(`[retry ${attempt + 1}/3 after ${wait}ms] network error: ${err.message}`)
      await sleep(wait)
      return query(sql, attempt + 1)
    }
    throw err
  }
  if (res.status >= 500 && attempt < 3) {
    const body = await res.text()
    const wait = 500 * Math.pow(3, attempt)
    console.error(`[retry ${attempt + 1}/3 after ${wait}ms] ${res.status}: ${body.slice(0, 120)}`)
    await sleep(wait)
    return query(sql, attempt + 1)
  }
  if (!res.ok) {
    const body = await res.text()
    throw new Error(`Management API ${res.status}: ${body}`)
  }
  return res.json()
}

const buffer = []
function emit(line) {
  buffer.push(line)
}

function section(title) {
  emit('')
  emit('-- ' + '='.repeat(76))
  emit('-- ' + title)
  emit('-- ' + '='.repeat(76))
}

async function main() {
  emit('-- BASELINE — schéma prod hand-curated via API Management (no Docker).')
  emit('-- Generated by scripts/export-schema.mjs on ' + new Date().toISOString())
  emit('-- Project: ' + PROJECT_REF)
  emit('--')
  emit("-- This file represents the public schema as it exists in the linked")
  emit("-- Supabase project at the timestamp above. It is NOT a pg_dump output;")
  emit("-- some advanced features (custom types beyond enums, MVs, granular grants")
  emit("-- on non-RLS tables) may be missing. Functions/RPCs are intentionally")
  emit("-- excluded — they live in their own migrations (e.g. 20260506000000_*).")
  emit('--')
  emit('-- Re-running scripts/export-schema.mjs against the same DB should produce')
  emit('-- a near-identical file (timestamps in CREATE INDEX names may shift).')

  // -------------------------------------------------------------------------
  // EXTENSIONS
  // -------------------------------------------------------------------------
  section('Extensions')
  const exts = await query(`
    SELECT extname, extversion
      FROM pg_extension
     WHERE extname NOT IN ('plpgsql')
     ORDER BY extname;
  `)
  for (const ext of exts) {
    emit(`CREATE EXTENSION IF NOT EXISTS "${ext.extname}";`)
  }

  // -------------------------------------------------------------------------
  // ENUMS
  // -------------------------------------------------------------------------
  section('Enums')
  const enums = await query(`
    SELECT t.typname AS name,
           array_agg(e.enumlabel ORDER BY e.enumsortorder) AS labels
      FROM pg_type t
      JOIN pg_enum e ON e.enumtypid = t.oid
      JOIN pg_namespace n ON n.oid = t.typnamespace
     WHERE n.nspname = 'public'
     GROUP BY t.typname
     ORDER BY t.typname;
  `)
  if (enums.length === 0) {
    emit('-- (no enums)')
  }
  for (const e of enums) {
    const labels = e.labels.map((l) => `'${l.replace(/'/g, "''")}'`).join(', ')
    emit(`CREATE TYPE "${e.name}" AS ENUM (${labels});`)
  }

  // -------------------------------------------------------------------------
  // TABLES
  // -------------------------------------------------------------------------
  section('Tables')
  const tables = await query(`
    SELECT tablename FROM pg_tables
     WHERE schemaname = 'public'
     ORDER BY tablename;
  `)

  for (const { tablename } of tables) {
    const cols = await query(`
      SELECT column_name,
             data_type,
             udt_name,
             character_maximum_length,
             numeric_precision,
             numeric_scale,
             is_nullable,
             column_default
        FROM information_schema.columns
       WHERE table_schema = 'public' AND table_name = '${tablename}'
       ORDER BY ordinal_position;
    `)
    emit('')
    emit(`CREATE TABLE IF NOT EXISTS "${tablename}" (`)
    const lines = cols.map((c) => {
      let type = c.data_type
      if (type === 'USER-DEFINED') type = `"${c.udt_name}"`
      else if (type === 'character varying' && c.character_maximum_length)
        type = `varchar(${c.character_maximum_length})`
      else if (type === 'numeric' && c.numeric_precision)
        type = c.numeric_scale != null
          ? `numeric(${c.numeric_precision}, ${c.numeric_scale})`
          : `numeric(${c.numeric_precision})`
      else if (type === 'ARRAY') type = `${c.udt_name.replace(/^_/, '')}[]`

      let s = `  "${c.column_name}" ${type}`
      if (c.is_nullable === 'NO') s += ' NOT NULL'
      if (c.column_default !== null) s += ` DEFAULT ${c.column_default}`
      return s
    })
    emit(lines.join(',\n'))
    emit(');')
  }

  // -------------------------------------------------------------------------
  // PRIMARY KEYS / UNIQUE
  // -------------------------------------------------------------------------
  section('Primary keys and unique constraints')
  const pkUnique = await query(`
    SELECT conrelid::regclass::text AS table_name,
           conname,
           contype,
           pg_get_constraintdef(oid) AS def
      FROM pg_constraint
     WHERE connamespace = 'public'::regnamespace
       AND contype IN ('p', 'u')
     ORDER BY conrelid::regclass::text, conname;
  `)
  for (const c of pkUnique) {
    const t = c.table_name.replace(/^public\./, '')
    emit(`ALTER TABLE "${t}" ADD CONSTRAINT "${c.conname}" ${c.def};`)
  }

  // -------------------------------------------------------------------------
  // FOREIGN KEYS
  // -------------------------------------------------------------------------
  section('Foreign keys')
  const fks = await query(`
    SELECT conrelid::regclass::text AS table_name,
           conname,
           pg_get_constraintdef(oid) AS def
      FROM pg_constraint
     WHERE connamespace = 'public'::regnamespace
       AND contype = 'f'
     ORDER BY conrelid::regclass::text, conname;
  `)
  for (const c of fks) {
    const t = c.table_name.replace(/^public\./, '')
    emit(`ALTER TABLE "${t}" ADD CONSTRAINT "${c.conname}" ${c.def};`)
  }

  // -------------------------------------------------------------------------
  // CHECK CONSTRAINTS
  // -------------------------------------------------------------------------
  section('Check constraints')
  const checks = await query(`
    SELECT conrelid::regclass::text AS table_name,
           conname,
           pg_get_constraintdef(oid) AS def
      FROM pg_constraint
     WHERE connamespace = 'public'::regnamespace
       AND contype = 'c'
     ORDER BY conrelid::regclass::text, conname;
  `)
  if (checks.length === 0) emit('-- (no CHECK constraints)')
  for (const c of checks) {
    const t = c.table_name.replace(/^public\./, '')
    emit(`ALTER TABLE "${t}" ADD CONSTRAINT "${c.conname}" ${c.def};`)
  }

  // -------------------------------------------------------------------------
  // INDEXES (excluding implicit ones from PK/UNIQUE constraints)
  // -------------------------------------------------------------------------
  section('Indexes (non-implicit)')
  const indexes = await query(`
    SELECT i.tablename, i.indexname, i.indexdef
      FROM pg_indexes i
      LEFT JOIN pg_constraint c
        ON c.conname = i.indexname
       AND c.connamespace = 'public'::regnamespace
     WHERE i.schemaname = 'public'
       AND c.conname IS NULL
     ORDER BY i.tablename, i.indexname;
  `)
  if (indexes.length === 0) emit('-- (no non-implicit indexes)')
  for (const idx of indexes) {
    emit(`${idx.indexdef};`)
  }

  // -------------------------------------------------------------------------
  // RLS — enable
  // -------------------------------------------------------------------------
  section('Row Level Security — enable')
  const rls = await query(`
    SELECT tablename FROM pg_tables
     WHERE schemaname = 'public' AND rowsecurity = true
     ORDER BY tablename;
  `)
  for (const { tablename } of rls) {
    emit(`ALTER TABLE "${tablename}" ENABLE ROW LEVEL SECURITY;`)
  }

  // -------------------------------------------------------------------------
  // POLICIES
  // -------------------------------------------------------------------------
  section('Row Level Security — policies')
  const policies = await query(`
    SELECT tablename, policyname, permissive, roles, cmd, qual, with_check
      FROM pg_policies
     WHERE schemaname = 'public'
     ORDER BY tablename, policyname;
  `)
  for (const p of policies) {
    let rolesArr = []
    if (Array.isArray(p.roles)) rolesArr = p.roles
    else if (typeof p.roles === 'string')
      rolesArr = p.roles.replace(/^\{|\}$/g, '').split(',').filter(Boolean)
    const rolesClause =
      rolesArr.length === 0 || (rolesArr.length === 1 && rolesArr[0] === 'public')
        ? ''
        : `\n  TO ${rolesArr.map((r) => r).join(', ')}`
    let permClause = ''
    if (p.permissive && p.permissive.toLowerCase() === 'restrictive') permClause = ' AS RESTRICTIVE'
    const usingClause = p.qual ? `\n  USING (${p.qual})` : ''
    const checkClause = p.with_check ? `\n  WITH CHECK (${p.with_check})` : ''
    emit(
      `CREATE POLICY "${p.policyname}"\n  ON "${p.tablename}"${permClause}\n  FOR ${p.cmd}${rolesClause}${usingClause}${checkClause};`
    )
  }

  // -------------------------------------------------------------------------
  // TRIGGERS
  // -------------------------------------------------------------------------
  section('Triggers')
  const triggers = await query(`
    SELECT tgname, tgrelid::regclass::text AS table_name,
           pg_get_triggerdef(oid) AS def
      FROM pg_trigger
     WHERE NOT tgisinternal
       AND tgrelid::regclass::text LIKE 'public.%'
     ORDER BY tgrelid::regclass::text, tgname;
  `)
  if (triggers.length === 0) emit('-- (no user triggers)')
  for (const t of triggers) {
    emit(`${t.def};`)
  }

  emit('')
  emit('-- END OF BASELINE')

  const output = buffer.join('\n') + '\n'
  if (OUT_PATH) {
    writeFileSync(OUT_PATH, output, { encoding: 'utf8' })
    console.error(`Wrote ${output.length} bytes to ${OUT_PATH}`)
  } else {
    process.stdout.write(output)
  }
}

main().catch((err) => {
  console.error('FATAL:', err.message)
  process.exit(1)
})
