-- BASELINE — schéma prod hand-curated via API Management (no Docker).
-- Generated by scripts/export-schema.mjs on 2026-05-26T07:12:54.790Z
-- Project: ddehmjucyfgyppfkbddr
--
-- This file represents the public schema as it exists in the linked
-- Supabase project at the timestamp above. It is NOT a pg_dump output;
-- some advanced features (custom types beyond enums, MVs, granular grants
-- on non-RLS tables) may be missing. Functions/RPCs are intentionally
-- excluded — they live in their own migrations (e.g. 20260506000000_*).
--
-- Re-running scripts/export-schema.mjs against the same DB should produce
-- a near-identical file (timestamps in CREATE INDEX names may shift).

-- ============================================================================
-- Extensions
-- ============================================================================
CREATE EXTENSION IF NOT EXISTS "pg_graphql";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "supabase_vault";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- Enums
-- ============================================================================
-- (no enums)

-- ============================================================================
-- Tables
-- ============================================================================

CREATE TABLE IF NOT EXISTS "bank_balances" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "profile_id" uuid,
  "balance" numeric NOT NULL DEFAULT 0,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  "group_id" uuid,
  "current_remaining_to_live" numeric DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "budget_transfers" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "from_budget_id" uuid,
  "to_budget_id" uuid NOT NULL,
  "transfer_amount" numeric NOT NULL,
  "transfer_reason" text DEFAULT 'Manual transfer'::text,
  "created_at" timestamp with time zone DEFAULT now(),
  "profile_id" uuid,
  "group_id" uuid,
  "transfer_date" date NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS "estimated_budgets" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "profile_id" uuid,
  "group_id" uuid,
  "name" text NOT NULL,
  "estimated_amount" numeric NOT NULL,
  "is_monthly_recurring" boolean NOT NULL DEFAULT true,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  "monthly_surplus" numeric DEFAULT 0,
  "monthly_deficit" numeric DEFAULT 0,
  "last_monthly_update" date,
  "carryover_spent_amount" numeric DEFAULT 0,
  "carryover_applied_date" date,
  "cumulated_savings" numeric DEFAULT 0,
  "last_savings_update" date,
  "last_surplus_transfer_date" date
);

CREATE TABLE IF NOT EXISTS "estimated_incomes" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "profile_id" uuid,
  "group_id" uuid,
  "name" text NOT NULL,
  "estimated_amount" numeric NOT NULL,
  "is_monthly_recurring" boolean NOT NULL DEFAULT true,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "expense_savings_sources" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "real_expense_id" uuid NOT NULL,
  "source_type" text NOT NULL,
  "source_budget_id" uuid,
  "amount" numeric(10, 2) NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "group_contributions" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "profile_id" uuid NOT NULL,
  "group_id" uuid NOT NULL,
  "salary" numeric(10, 2) NOT NULL,
  "contribution_amount" numeric(10, 2) NOT NULL,
  "contribution_percentage" numeric(5, 2) NOT NULL,
  "calculated_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "groups" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "name" text NOT NULL,
  "monthly_budget_estimate" numeric(10, 2) NOT NULL,
  "creator_id" uuid NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "monthly_recaps" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "profile_id" uuid,
  "group_id" uuid,
  "recap_month" smallint NOT NULL,
  "recap_year" smallint NOT NULL,
  "current_step" text NOT NULL DEFAULT 'welcome'::text,
  "started_by_profile_id" uuid,
  "started_at" timestamp with time zone,
  "refloated_from_piggy" numeric(14, 2) NOT NULL DEFAULT 0,
  "refloated_from_savings" numeric(14, 2) NOT NULL DEFAULT 0,
  "budget_snapshot_data" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "completed_at" timestamp with time zone,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
  "piggy_transfers_data" jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS "piggy_bank" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "profile_id" uuid,
  "group_id" uuid,
  "amount" numeric(10, 2) NOT NULL DEFAULT 0,
  "last_updated" timestamp without time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "profiles" (
  "id" uuid NOT NULL,
  "first_name" text NOT NULL,
  "last_name" text NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  "group_id" uuid,
  "salary" numeric(10, 2) DEFAULT 0,
  "avatar_url" text
);

CREATE TABLE IF NOT EXISTS "real_expenses" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "profile_id" uuid,
  "group_id" uuid,
  "estimated_budget_id" uuid,
  "amount" numeric NOT NULL,
  "description" text NOT NULL,
  "expense_date" date NOT NULL DEFAULT CURRENT_DATE,
  "is_exceptional" boolean NOT NULL DEFAULT false,
  "created_at" timestamp with time zone DEFAULT now(),
  "amount_from_piggy_bank" numeric DEFAULT 0,
  "amount_from_budget_savings" numeric DEFAULT 0,
  "amount_from_budget" numeric DEFAULT 0,
  "created_by_profile_id" uuid,
  "applied_to_balance_at" timestamp with time zone,
  "is_carried_over" boolean NOT NULL DEFAULT false,
  "carried_from_recap_id" uuid,
  "contribution_id" uuid,
  "last_applied_amount" numeric(10, 2)
);

CREATE TABLE IF NOT EXISTS "real_income_entries" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "profile_id" uuid,
  "group_id" uuid,
  "estimated_income_id" uuid,
  "amount" numeric NOT NULL,
  "description" text NOT NULL,
  "entry_date" date NOT NULL DEFAULT CURRENT_DATE,
  "is_exceptional" boolean NOT NULL DEFAULT false,
  "created_at" timestamp with time zone DEFAULT now(),
  "created_by_profile_id" uuid,
  "applied_to_balance_at" timestamp with time zone,
  "is_carried_over" boolean NOT NULL DEFAULT false,
  "carried_from_recap_id" uuid,
  "last_applied_amount" numeric(10, 2)
);

CREATE TABLE IF NOT EXISTS "remaining_to_live_snapshots" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "profile_id" uuid,
  "group_id" uuid,
  "remaining_to_live" numeric NOT NULL,
  "available_balance" numeric NOT NULL,
  "total_savings" numeric NOT NULL,
  "total_estimated_income" numeric NOT NULL,
  "total_estimated_budgets" numeric NOT NULL,
  "total_real_income" numeric NOT NULL,
  "total_real_expenses" numeric NOT NULL,
  "snapshot_reason" text NOT NULL,
  "created_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "savings_projects" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "profile_id" uuid,
  "group_id" uuid,
  "name" text NOT NULL,
  "target_amount" numeric(12, 2) NOT NULL,
  "monthly_allocation" numeric(12, 2) NOT NULL,
  "deadline_date" date NOT NULL,
  "amount_saved" numeric(12, 2) NOT NULL DEFAULT 0,
  "pending_delay_fraction" numeric(6, 4) NOT NULL DEFAULT 0,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at" timestamp with time zone NOT NULL DEFAULT now()
);

-- ============================================================================
-- Primary keys and unique constraints
-- ============================================================================
ALTER TABLE "bank_balances" ADD CONSTRAINT "bank_balances_pkey" PRIMARY KEY (id);
ALTER TABLE "budget_transfers" ADD CONSTRAINT "budget_transfers_pkey" PRIMARY KEY (id);
ALTER TABLE "estimated_budgets" ADD CONSTRAINT "estimated_budgets_pkey" PRIMARY KEY (id);
ALTER TABLE "estimated_incomes" ADD CONSTRAINT "estimated_incomes_pkey" PRIMARY KEY (id);
ALTER TABLE "expense_savings_sources" ADD CONSTRAINT "expense_savings_sources_pkey" PRIMARY KEY (id);
ALTER TABLE "group_contributions" ADD CONSTRAINT "group_contributions_pkey" PRIMARY KEY (id);
ALTER TABLE "group_contributions" ADD CONSTRAINT "group_contributions_unique_profile_group" UNIQUE (profile_id, group_id);
ALTER TABLE "groups" ADD CONSTRAINT "groups_name_key" UNIQUE (name);
ALTER TABLE "groups" ADD CONSTRAINT "groups_pkey" PRIMARY KEY (id);
ALTER TABLE "monthly_recaps" ADD CONSTRAINT "monthly_recaps_pkey" PRIMARY KEY (id);
ALTER TABLE "piggy_bank" ADD CONSTRAINT "piggy_bank_pkey" PRIMARY KEY (id);
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_pkey" PRIMARY KEY (id);
ALTER TABLE "real_expenses" ADD CONSTRAINT "real_expenses_pkey" PRIMARY KEY (id);
ALTER TABLE "real_income_entries" ADD CONSTRAINT "real_income_entries_pkey" PRIMARY KEY (id);
ALTER TABLE "remaining_to_live_snapshots" ADD CONSTRAINT "remaining_to_live_snapshots_pkey" PRIMARY KEY (id);
ALTER TABLE "savings_projects" ADD CONSTRAINT "savings_projects_pkey" PRIMARY KEY (id);

-- ============================================================================
-- Foreign keys
-- ============================================================================
ALTER TABLE "bank_balances" ADD CONSTRAINT "bank_balances_group_id_fkey" FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;
ALTER TABLE "bank_balances" ADD CONSTRAINT "bank_balances_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "budget_transfers" ADD CONSTRAINT "budget_transfers_from_budget_fkey" FOREIGN KEY (from_budget_id) REFERENCES estimated_budgets(id) ON DELETE CASCADE;
ALTER TABLE "budget_transfers" ADD CONSTRAINT "budget_transfers_group_id_fkey" FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;
ALTER TABLE "budget_transfers" ADD CONSTRAINT "budget_transfers_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE "budget_transfers" ADD CONSTRAINT "budget_transfers_to_budget_fkey" FOREIGN KEY (to_budget_id) REFERENCES estimated_budgets(id) ON DELETE CASCADE;
ALTER TABLE "estimated_budgets" ADD CONSTRAINT "estimated_budgets_group_id_fkey" FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;
ALTER TABLE "estimated_budgets" ADD CONSTRAINT "estimated_budgets_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE "estimated_incomes" ADD CONSTRAINT "estimated_incomes_group_id_fkey" FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;
ALTER TABLE "estimated_incomes" ADD CONSTRAINT "estimated_incomes_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE "expense_savings_sources" ADD CONSTRAINT "expense_savings_sources_real_expense_id_fkey" FOREIGN KEY (real_expense_id) REFERENCES real_expenses(id) ON DELETE CASCADE;
ALTER TABLE "expense_savings_sources" ADD CONSTRAINT "expense_savings_sources_source_budget_id_fkey" FOREIGN KEY (source_budget_id) REFERENCES estimated_budgets(id) ON DELETE SET NULL;
ALTER TABLE "group_contributions" ADD CONSTRAINT "group_contributions_group_id_fkey" FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;
ALTER TABLE "group_contributions" ADD CONSTRAINT "group_contributions_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE "groups" ADD CONSTRAINT "groups_creator_id_fkey" FOREIGN KEY (creator_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "monthly_recaps" ADD CONSTRAINT "monthly_recaps_group_id_fkey" FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;
ALTER TABLE "monthly_recaps" ADD CONSTRAINT "monthly_recaps_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE "monthly_recaps" ADD CONSTRAINT "monthly_recaps_started_by_profile_id_fkey" FOREIGN KEY (started_by_profile_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE "piggy_bank" ADD CONSTRAINT "piggy_bank_group_id_fkey" FOREIGN KEY (group_id) REFERENCES groups(id);
ALTER TABLE "piggy_bank" ADD CONSTRAINT "piggy_bank_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id);
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_group_id_fkey" FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE SET NULL;
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "real_expenses" ADD CONSTRAINT "real_expenses_carried_from_recap_id_fkey" FOREIGN KEY (carried_from_recap_id) REFERENCES monthly_recaps(id) ON DELETE SET NULL;
ALTER TABLE "real_expenses" ADD CONSTRAINT "real_expenses_contribution_id_fkey" FOREIGN KEY (contribution_id) REFERENCES group_contributions(id) ON DELETE CASCADE;
ALTER TABLE "real_expenses" ADD CONSTRAINT "real_expenses_created_by_profile_id_fkey" FOREIGN KEY (created_by_profile_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE "real_expenses" ADD CONSTRAINT "real_expenses_estimated_budget_id_fkey" FOREIGN KEY (estimated_budget_id) REFERENCES estimated_budgets(id) ON DELETE SET NULL;
ALTER TABLE "real_expenses" ADD CONSTRAINT "real_expenses_group_id_fkey" FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;
ALTER TABLE "real_expenses" ADD CONSTRAINT "real_expenses_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE "real_income_entries" ADD CONSTRAINT "real_income_entries_carried_from_recap_id_fkey" FOREIGN KEY (carried_from_recap_id) REFERENCES monthly_recaps(id) ON DELETE SET NULL;
ALTER TABLE "real_income_entries" ADD CONSTRAINT "real_income_entries_created_by_profile_id_fkey" FOREIGN KEY (created_by_profile_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE "real_income_entries" ADD CONSTRAINT "real_income_entries_estimated_income_id_fkey" FOREIGN KEY (estimated_income_id) REFERENCES estimated_incomes(id) ON DELETE SET NULL;
ALTER TABLE "real_income_entries" ADD CONSTRAINT "real_income_entries_group_id_fkey" FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;
ALTER TABLE "real_income_entries" ADD CONSTRAINT "real_income_entries_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE "remaining_to_live_snapshots" ADD CONSTRAINT "remaining_to_live_snapshots_group_id_fkey" FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;
ALTER TABLE "remaining_to_live_snapshots" ADD CONSTRAINT "remaining_to_live_snapshots_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE "savings_projects" ADD CONSTRAINT "savings_projects_group_id_fkey" FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE;
ALTER TABLE "savings_projects" ADD CONSTRAINT "savings_projects_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;

-- ============================================================================
-- Check constraints
-- ============================================================================
ALTER TABLE "bank_balances" ADD CONSTRAINT "bank_balances_owner_exclusive_check" CHECK ((((profile_id IS NOT NULL) AND (group_id IS NULL)) OR ((profile_id IS NULL) AND (group_id IS NOT NULL))));
ALTER TABLE "budget_transfers" ADD CONSTRAINT "budget_transfers_different_budgets_check" CHECK (((from_budget_id IS NULL) OR (from_budget_id <> to_budget_id)));
ALTER TABLE "budget_transfers" ADD CONSTRAINT "budget_transfers_owner_exclusive_check" CHECK ((((profile_id IS NOT NULL) AND (group_id IS NULL)) OR ((profile_id IS NULL) AND (group_id IS NOT NULL))));
ALTER TABLE "budget_transfers" ADD CONSTRAINT "budget_transfers_transfer_amount_check" CHECK ((transfer_amount > (0)::numeric));
ALTER TABLE "estimated_budgets" ADD CONSTRAINT "estimated_budgets_carryover_spent_amount_check" CHECK ((carryover_spent_amount >= (0)::numeric));
ALTER TABLE "estimated_budgets" ADD CONSTRAINT "estimated_budgets_cumulated_savings_check" CHECK ((cumulated_savings >= (0)::numeric));
ALTER TABLE "estimated_budgets" ADD CONSTRAINT "estimated_budgets_estimated_amount_check" CHECK ((estimated_amount >= (0)::numeric));
ALTER TABLE "estimated_budgets" ADD CONSTRAINT "estimated_budgets_monthly_deficit_check" CHECK ((monthly_deficit >= (0)::numeric));
ALTER TABLE "estimated_budgets" ADD CONSTRAINT "estimated_budgets_monthly_surplus_check" CHECK ((monthly_surplus >= (0)::numeric));
ALTER TABLE "estimated_budgets" ADD CONSTRAINT "estimated_budgets_name_not_empty_check" CHECK ((TRIM(BOTH FROM name) <> ''::text));
ALTER TABLE "estimated_budgets" ADD CONSTRAINT "estimated_budgets_owner_exclusive_check" CHECK ((((profile_id IS NOT NULL) AND (group_id IS NULL)) OR ((profile_id IS NULL) AND (group_id IS NOT NULL))));
ALTER TABLE "estimated_incomes" ADD CONSTRAINT "estimated_incomes_estimated_amount_check" CHECK ((estimated_amount >= (0)::numeric));
ALTER TABLE "estimated_incomes" ADD CONSTRAINT "estimated_incomes_name_not_empty_check" CHECK ((TRIM(BOTH FROM name) <> ''::text));
ALTER TABLE "estimated_incomes" ADD CONSTRAINT "estimated_incomes_nonnegative_amount_check" CHECK ((estimated_amount >= (0)::numeric));
ALTER TABLE "estimated_incomes" ADD CONSTRAINT "estimated_incomes_owner_exclusive_check" CHECK ((((profile_id IS NOT NULL) AND (group_id IS NULL)) OR ((profile_id IS NULL) AND (group_id IS NOT NULL))));
ALTER TABLE "expense_savings_sources" ADD CONSTRAINT "expense_savings_sources_amount_check" CHECK ((amount > (0)::numeric));
ALTER TABLE "expense_savings_sources" ADD CONSTRAINT "expense_savings_sources_coherence_check" CHECK ((((source_type = 'piggy'::text) AND (source_budget_id IS NULL)) OR ((source_type = 'budget_savings'::text) AND (source_budget_id IS NOT NULL))));
ALTER TABLE "expense_savings_sources" ADD CONSTRAINT "expense_savings_sources_source_type_check" CHECK ((source_type = ANY (ARRAY['piggy'::text, 'budget_savings'::text])));
ALTER TABLE "group_contributions" ADD CONSTRAINT "group_contributions_amount_positive" CHECK ((contribution_amount >= (0)::numeric));
ALTER TABLE "group_contributions" ADD CONSTRAINT "group_contributions_percentage_positive" CHECK ((contribution_percentage >= (0)::numeric));
ALTER TABLE "group_contributions" ADD CONSTRAINT "group_contributions_salary_positive" CHECK ((salary >= (0)::numeric));
ALTER TABLE "monthly_recaps" ADD CONSTRAINT "monthly_recaps_current_step_check" CHECK ((current_step = ANY (ARRAY['welcome'::text, 'complete_month'::text, 'summary'::text, 'manage_bilan'::text, 'salary_update'::text, 'final_recap'::text, 'completed'::text])));
ALTER TABLE "monthly_recaps" ADD CONSTRAINT "monthly_recaps_owner_exclusive_check" CHECK ((((profile_id IS NOT NULL) AND (group_id IS NULL)) OR ((profile_id IS NULL) AND (group_id IS NOT NULL))));
ALTER TABLE "monthly_recaps" ADD CONSTRAINT "monthly_recaps_recap_month_check" CHECK (((recap_month >= 1) AND (recap_month <= 12)));
ALTER TABLE "monthly_recaps" ADD CONSTRAINT "monthly_recaps_recap_year_check" CHECK (((recap_year >= 2024) AND (recap_year <= 2100)));
ALTER TABLE "piggy_bank" ADD CONSTRAINT "piggy_bank_amount_check" CHECK ((amount >= (0)::numeric));
ALTER TABLE "piggy_bank" ADD CONSTRAINT "piggy_bank_owner_exclusive_check" CHECK ((((profile_id IS NOT NULL) AND (group_id IS NULL)) OR ((profile_id IS NULL) AND (group_id IS NOT NULL))));
ALTER TABLE "real_expenses" ADD CONSTRAINT "real_expenses_amount_check" CHECK ((amount > (0)::numeric));
ALTER TABLE "real_expenses" ADD CONSTRAINT "real_expenses_amount_from_budget_check" CHECK ((amount_from_budget >= (0)::numeric));
ALTER TABLE "real_expenses" ADD CONSTRAINT "real_expenses_amount_from_budget_savings_check" CHECK ((amount_from_budget_savings >= (0)::numeric));
ALTER TABLE "real_expenses" ADD CONSTRAINT "real_expenses_amount_from_piggy_bank_check" CHECK ((amount_from_piggy_bank >= (0)::numeric));
ALTER TABLE "real_expenses" ADD CONSTRAINT "real_expenses_owner_exclusive_check" CHECK ((((profile_id IS NOT NULL) AND (group_id IS NULL)) OR ((profile_id IS NULL) AND (group_id IS NOT NULL))));
ALTER TABLE "real_income_entries" ADD CONSTRAINT "real_income_entries_amount_check" CHECK ((amount > (0)::numeric));
ALTER TABLE "real_income_entries" ADD CONSTRAINT "real_income_entries_owner_exclusive_check" CHECK ((((profile_id IS NOT NULL) AND (group_id IS NULL)) OR ((profile_id IS NULL) AND (group_id IS NOT NULL))));
ALTER TABLE "remaining_to_live_snapshots" ADD CONSTRAINT "remaining_to_live_snapshots_owner_exclusive_check" CHECK ((((profile_id IS NOT NULL) AND (group_id IS NULL)) OR ((profile_id IS NULL) AND (group_id IS NOT NULL))));
ALTER TABLE "savings_projects" ADD CONSTRAINT "savings_projects_amount_saved_check" CHECK ((amount_saved >= (0)::numeric));
ALTER TABLE "savings_projects" ADD CONSTRAINT "savings_projects_monthly_positive_check" CHECK ((monthly_allocation > (0)::numeric));
ALTER TABLE "savings_projects" ADD CONSTRAINT "savings_projects_name_min_len_check" CHECK ((length(TRIM(BOTH FROM name)) >= 2));
ALTER TABLE "savings_projects" ADD CONSTRAINT "savings_projects_name_not_empty_check" CHECK ((TRIM(BOTH FROM name) <> ''::text));
ALTER TABLE "savings_projects" ADD CONSTRAINT "savings_projects_owner_exclusive_check" CHECK ((((profile_id IS NOT NULL) AND (group_id IS NULL)) OR ((profile_id IS NULL) AND (group_id IS NOT NULL))));
ALTER TABLE "savings_projects" ADD CONSTRAINT "savings_projects_pending_delay_range_check" CHECK (((pending_delay_fraction >= (0)::numeric) AND (pending_delay_fraction < (1)::numeric)));
ALTER TABLE "savings_projects" ADD CONSTRAINT "savings_projects_target_positive_check" CHECK ((target_amount > (0)::numeric));

-- ============================================================================
-- Indexes (non-implicit)
-- ============================================================================
CREATE INDEX idx_bank_balances_group_id ON public.bank_balances USING btree (group_id) WHERE (group_id IS NOT NULL);
CREATE UNIQUE INDEX idx_bank_balances_group_id_unique ON public.bank_balances USING btree (group_id) WHERE (group_id IS NOT NULL);
CREATE INDEX idx_bank_balances_group_rav ON public.bank_balances USING btree (group_id, current_remaining_to_live) WHERE (group_id IS NOT NULL);
CREATE UNIQUE INDEX idx_bank_balances_profile_id_unique ON public.bank_balances USING btree (profile_id) WHERE (profile_id IS NOT NULL);
CREATE INDEX idx_bank_balances_profile_rav ON public.bank_balances USING btree (profile_id, current_remaining_to_live) WHERE (profile_id IS NOT NULL);
CREATE INDEX budget_transfers_group_id_idx ON public.budget_transfers USING btree (group_id);
CREATE INDEX budget_transfers_profile_id_idx ON public.budget_transfers USING btree (profile_id);
CREATE INDEX budget_transfers_transfer_date_idx ON public.budget_transfers USING btree (transfer_date);
CREATE INDEX idx_budget_transfers_from_budget ON public.budget_transfers USING btree (from_budget_id);
CREATE INDEX idx_budget_transfers_to_budget ON public.budget_transfers USING btree (to_budget_id);
CREATE INDEX idx_estimated_budgets_amount ON public.estimated_budgets USING btree (profile_id, group_id, estimated_amount);
CREATE INDEX idx_estimated_budgets_group_id ON public.estimated_budgets USING btree (group_id) WHERE (group_id IS NOT NULL);
CREATE INDEX idx_estimated_budgets_profile_id ON public.estimated_budgets USING btree (profile_id) WHERE (profile_id IS NOT NULL);
CREATE INDEX idx_estimated_incomes_group_id ON public.estimated_incomes USING btree (group_id) WHERE (group_id IS NOT NULL);
CREATE INDEX idx_estimated_incomes_monthly_recurring ON public.estimated_incomes USING btree (profile_id, group_id) WHERE (is_monthly_recurring = true);
CREATE INDEX idx_estimated_incomes_profile_id ON public.estimated_incomes USING btree (profile_id) WHERE (profile_id IS NOT NULL);
CREATE INDEX idx_expense_savings_sources_real_expense ON public.expense_savings_sources USING btree (real_expense_id);
CREATE INDEX idx_expense_savings_sources_source_budget ON public.expense_savings_sources USING btree (source_budget_id) WHERE (source_budget_id IS NOT NULL);
CREATE INDEX idx_group_contributions_calculated_at ON public.group_contributions USING btree (calculated_at);
CREATE INDEX idx_group_contributions_group_id ON public.group_contributions USING btree (group_id);
CREATE INDEX idx_group_contributions_profile_id ON public.group_contributions USING btree (profile_id);
CREATE INDEX monthly_recaps_completed_lookup ON public.monthly_recaps USING btree (profile_id, group_id, recap_month, recap_year, completed_at);
CREATE UNIQUE INDEX monthly_recaps_group_unique ON public.monthly_recaps USING btree (group_id, recap_month, recap_year) WHERE (group_id IS NOT NULL);
CREATE UNIQUE INDEX monthly_recaps_profile_unique ON public.monthly_recaps USING btree (profile_id, recap_month, recap_year) WHERE (profile_id IS NOT NULL);
CREATE UNIQUE INDEX idx_piggy_bank_group_id_unique ON public.piggy_bank USING btree (group_id) WHERE ((group_id IS NOT NULL) AND (profile_id IS NULL));
CREATE UNIQUE INDEX idx_piggy_bank_profile_id_unique ON public.piggy_bank USING btree (profile_id) WHERE ((profile_id IS NOT NULL) AND (group_id IS NULL));
CREATE INDEX idx_profiles_group_id ON public.profiles USING btree (group_id);
CREATE INDEX idx_real_expenses_applied_to_balance ON public.real_expenses USING btree (applied_to_balance_at) WHERE (applied_to_balance_at IS NOT NULL);
CREATE INDEX idx_real_expenses_budget_month ON public.real_expenses USING btree (estimated_budget_id, expense_date) WHERE (estimated_budget_id IS NOT NULL);
CREATE INDEX idx_real_expenses_created_by_profile_id ON public.real_expenses USING btree (created_by_profile_id);
CREATE INDEX idx_real_expenses_estimated_budget_id ON public.real_expenses USING btree (estimated_budget_id) WHERE (estimated_budget_id IS NOT NULL);
CREATE INDEX idx_real_expenses_exceptional ON public.real_expenses USING btree (profile_id, group_id) WHERE (is_exceptional = true);
CREATE INDEX idx_real_expenses_expense_date ON public.real_expenses USING btree (expense_date);
CREATE INDEX idx_real_expenses_group_date ON public.real_expenses USING btree (group_id, expense_date) WHERE (group_id IS NOT NULL);
CREATE INDEX idx_real_expenses_group_id ON public.real_expenses USING btree (group_id) WHERE (group_id IS NOT NULL);
CREATE INDEX idx_real_expenses_profile_date ON public.real_expenses USING btree (profile_id, expense_date) WHERE (profile_id IS NOT NULL);
CREATE INDEX idx_real_expenses_profile_id ON public.real_expenses USING btree (profile_id) WHERE (profile_id IS NOT NULL);
CREATE INDEX real_expenses_carried_over_idx ON public.real_expenses USING btree (profile_id, group_id, is_carried_over) WHERE (is_carried_over = true);
CREATE UNIQUE INDEX real_expenses_contribution_id_uniq ON public.real_expenses USING btree (contribution_id) WHERE (contribution_id IS NOT NULL);
CREATE INDEX idx_real_income_entries_applied_to_balance ON public.real_income_entries USING btree (applied_to_balance_at) WHERE (applied_to_balance_at IS NOT NULL);
CREATE INDEX idx_real_income_entries_created_by_profile_id ON public.real_income_entries USING btree (created_by_profile_id);
CREATE INDEX idx_real_income_entries_entry_date ON public.real_income_entries USING btree (entry_date);
CREATE INDEX idx_real_income_entries_estimated_id ON public.real_income_entries USING btree (estimated_income_id) WHERE (estimated_income_id IS NOT NULL);
CREATE INDEX idx_real_income_entries_group_date ON public.real_income_entries USING btree (group_id, entry_date) WHERE (group_id IS NOT NULL);
CREATE INDEX idx_real_income_entries_group_id ON public.real_income_entries USING btree (group_id) WHERE (group_id IS NOT NULL);
CREATE INDEX idx_real_income_entries_profile_date ON public.real_income_entries USING btree (profile_id, entry_date) WHERE (profile_id IS NOT NULL);
CREATE INDEX idx_real_income_entries_profile_id ON public.real_income_entries USING btree (profile_id) WHERE (profile_id IS NOT NULL);
CREATE INDEX real_income_entries_carried_over_idx ON public.real_income_entries USING btree (profile_id, group_id, is_carried_over) WHERE (is_carried_over = true);
CREATE INDEX idx_remaining_to_live_snapshots_group_date ON public.remaining_to_live_snapshots USING btree (group_id, created_at DESC) WHERE (group_id IS NOT NULL);
CREATE INDEX idx_remaining_to_live_snapshots_profile_date ON public.remaining_to_live_snapshots USING btree (profile_id, created_at DESC) WHERE (profile_id IS NOT NULL);
CREATE INDEX idx_savings_projects_group_id ON public.savings_projects USING btree (group_id) WHERE (group_id IS NOT NULL);
CREATE INDEX idx_savings_projects_profile_id ON public.savings_projects USING btree (profile_id) WHERE (profile_id IS NOT NULL);

-- ============================================================================
-- Row Level Security — enable
-- ============================================================================
ALTER TABLE "bank_balances" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "budget_transfers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "estimated_budgets" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "estimated_incomes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "expense_savings_sources" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "group_contributions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "groups" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "monthly_recaps" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "piggy_bank" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "real_expenses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "real_income_entries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "remaining_to_live_snapshots" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "savings_projects" ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- Row Level Security — policies
-- ============================================================================
CREATE POLICY "Users can update their own bank balance"
  ON "bank_balances"
  FOR ALL
  USING ((auth.uid() = profile_id));
CREATE POLICY "Users can view their own bank balance"
  ON "bank_balances"
  FOR SELECT
  USING ((auth.uid() = profile_id));
CREATE POLICY "Users can delete their own budget transfers"
  ON "budget_transfers"
  FOR DELETE
  USING (((profile_id = auth.uid()) OR (group_id IN ( SELECT profiles.group_id
   FROM profiles
  WHERE (profiles.id = auth.uid())))));
CREATE POLICY "Users can insert their own budget transfers"
  ON "budget_transfers"
  FOR INSERT
  WITH CHECK ((((profile_id = auth.uid()) AND (group_id IS NULL)) OR ((group_id IN ( SELECT profiles.group_id
   FROM profiles
  WHERE (profiles.id = auth.uid()))) AND (profile_id IS NULL))));
CREATE POLICY "Users can update their own budget transfers"
  ON "budget_transfers"
  FOR UPDATE
  USING (((profile_id = auth.uid()) OR (group_id IN ( SELECT profiles.group_id
   FROM profiles
  WHERE (profiles.id = auth.uid())))));
CREATE POLICY "Users can view their own budget transfers"
  ON "budget_transfers"
  FOR SELECT
  USING (((profile_id = auth.uid()) OR (group_id IN ( SELECT profiles.group_id
   FROM profiles
  WHERE (profiles.id = auth.uid())))));
CREATE POLICY "Group members can manage group budgets"
  ON "estimated_budgets"
  FOR ALL
  USING (((group_id IS NOT NULL) AND (group_id IN ( SELECT profiles.group_id
   FROM profiles
  WHERE (profiles.id = auth.uid())))));
CREATE POLICY "Users can manage their own budgets"
  ON "estimated_budgets"
  FOR ALL
  USING ((profile_id = auth.uid()));
CREATE POLICY "Group members can manage group estimated incomes"
  ON "estimated_incomes"
  FOR ALL
  USING (((group_id IS NOT NULL) AND (group_id IN ( SELECT profiles.group_id
   FROM profiles
  WHERE (profiles.id = auth.uid())))));
CREATE POLICY "Users can manage their own estimated incomes"
  ON "estimated_incomes"
  FOR ALL
  USING ((profile_id = auth.uid()));
CREATE POLICY "Group members can manage their group contributions"
  ON "group_contributions"
  FOR ALL
  USING ((group_id IN ( SELECT profiles.group_id
   FROM profiles
  WHERE (profiles.id = auth.uid()))));
CREATE POLICY "Users can view contributions for their own group"
  ON "group_contributions"
  FOR SELECT
  USING ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.group_id = group_contributions.group_id)))));
CREATE POLICY "Creators can delete their groups"
  ON "groups"
  FOR DELETE
  TO authenticated
  USING ((creator_id = auth.uid()));
CREATE POLICY "Creators can update their groups"
  ON "groups"
  FOR UPDATE
  TO authenticated
  USING ((creator_id = auth.uid()));
CREATE POLICY "Users can create groups"
  ON "groups"
  FOR INSERT
  TO authenticated
  WITH CHECK ((creator_id = auth.uid()));
CREATE POLICY "Users can view all groups"
  ON "groups"
  FOR SELECT
  TO authenticated
  USING (true);
CREATE POLICY "Users can manage their own piggy_bank"
  ON "piggy_bank"
  FOR ALL
  USING (((profile_id = auth.uid()) OR ((group_id IS NOT NULL) AND (group_id IN ( SELECT profiles.group_id
   FROM profiles
  WHERE (profiles.id = auth.uid()))))));
CREATE POLICY "Users can view their own piggy_bank"
  ON "piggy_bank"
  FOR SELECT
  USING (((profile_id = auth.uid()) OR ((group_id IS NOT NULL) AND (group_id IN ( SELECT profiles.group_id
   FROM profiles
  WHERE (profiles.id = auth.uid()))))));
CREATE POLICY "Users can insert own profile"
  ON "profiles"
  FOR INSERT
  WITH CHECK ((auth.uid() = id));
CREATE POLICY "Users can read own profile"
  ON "profiles"
  FOR SELECT
  TO authenticated
  USING ((id = auth.uid()));
CREATE POLICY "Users can update own profile"
  ON "profiles"
  FOR UPDATE
  USING ((auth.uid() = id));
CREATE POLICY "Group members can manage group expenses"
  ON "real_expenses"
  FOR ALL
  USING (((group_id IS NOT NULL) AND (group_id IN ( SELECT profiles.group_id
   FROM profiles
  WHERE (profiles.id = auth.uid())))));
CREATE POLICY "Users can manage their own expenses"
  ON "real_expenses"
  FOR ALL
  USING ((profile_id = auth.uid()));
CREATE POLICY "Group members can manage group income entries"
  ON "real_income_entries"
  FOR ALL
  USING (((group_id IS NOT NULL) AND (group_id IN ( SELECT profiles.group_id
   FROM profiles
  WHERE (profiles.id = auth.uid())))));
CREATE POLICY "Users can manage their own income entries"
  ON "real_income_entries"
  FOR ALL
  USING ((profile_id = auth.uid()));
CREATE POLICY "Only service role can insert snapshots"
  ON "remaining_to_live_snapshots"
  FOR INSERT
  TO service_role
  WITH CHECK (true);
CREATE POLICY "Users can view their group remaining to live snapshots"
  ON "remaining_to_live_snapshots"
  FOR SELECT
  USING ((group_id IN ( SELECT profiles.group_id
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.group_id IS NOT NULL)))));
CREATE POLICY "Users can view their own remaining to live snapshots"
  ON "remaining_to_live_snapshots"
  FOR SELECT
  USING ((profile_id = auth.uid()));
CREATE POLICY "Group members can manage group savings projects"
  ON "savings_projects"
  FOR ALL
  USING (((group_id IS NOT NULL) AND (group_id IN ( SELECT profiles.group_id
   FROM profiles
  WHERE (profiles.id = auth.uid())))));
CREATE POLICY "Users can manage their own savings projects"
  ON "savings_projects"
  FOR ALL
  USING ((profile_id = auth.uid()));

-- ============================================================================
-- Triggers
-- ============================================================================
CREATE TRIGGER update_bank_balances_updated_at BEFORE UPDATE ON public.bank_balances FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER estimated_budgets_sync_group_budget AFTER INSERT OR DELETE OR UPDATE ON public.estimated_budgets FOR EACH ROW EXECUTE FUNCTION sync_group_monthly_budget_estimate();
CREATE TRIGGER group_contributions_sync_real_expense AFTER INSERT OR UPDATE ON public.group_contributions FOR EACH ROW EXECUTE FUNCTION sync_contribution_real_expense();
CREATE TRIGGER groups_budget_contribution_recalc AFTER UPDATE ON public.groups FOR EACH ROW EXECUTE FUNCTION trigger_group_budget_change();
CREATE TRIGGER groups_cleanup_contributions BEFORE DELETE ON public.groups FOR EACH ROW EXECUTE FUNCTION cleanup_group_contributions();
CREATE TRIGGER update_groups_updated_at BEFORE UPDATE ON public.groups FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_monthly_recaps_updated_at BEFORE UPDATE ON public.monthly_recaps FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER profiles_contribution_recalc AFTER INSERT OR DELETE OR UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION trigger_recalculate_contributions();
CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER real_expenses_credit_balance_on_contribution_delete BEFORE DELETE ON public.real_expenses FOR EACH ROW EXECUTE FUNCTION credit_balance_on_contribution_delete();
CREATE TRIGGER update_savings_projects_updated_at BEFORE UPDATE ON public.savings_projects FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- END OF BASELINE
